repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the latest stable tag
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 24.3.0 # Use the latest stable tag
    hooks:
      - id: black
  - repo: https://github.com/crate-ci/typos
    rev: v1.24.5
    hooks:
      - id: typos
  -   repo: https://github.com/python-poetry/poetry
      rev: '1.8.3'
      hooks:
      -   id: poetry-check
      -   id: poetry-lock
      -   id: poetry-install
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [ "--fix", "--exit-non-zero-on-fix" ]
